language: d
matrix:
    allow_failures:
        - d: gdc-4.9.2
        - d: ldc-0.16.1
    include:
        - d: dmd-2.069.2
          env: USE_DOVERALLS=true
        - d: gdc-4.9.2
        - d: ldc-0.16.1
  
script:
    - chmod +x travis-script.sh
    - ./travis-script.sh
